# Generated by Django 4.1.3 on 2022-11-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_music_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
