# Generated by Django 4.1.3 on 2022-11-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_music_list', '0002_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
